apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: student-project 
spec:
  selector:
    app: nodejs
  ports:
    - protocol:   TCP
      port:       4000
      targetPort: 4000
